Repository Inha-cc-01/AI, pull requests merged in 2025-06, with the labels that each got.

#13 [ICC-47] quiz parsing
  app/adapter/request_to_bedrock.py
  app/adapter/summary_bedrock.py
  app/dto/model/problem.py
  app/dto/model/selection.py
  app/dto/request/generate_request.py
  app/dto/response/generate_response.py
  app/service/generate_service.py
  app/util/create_chunks.py
  app/util/parsing.py
  requirements.txt
Labels: 구현

#14 [ICC-49] dependency 해결
  requirements.txt
Labels: 문서

#15 [ICC-50] API서버 연결 간 문제 해결
  app/dto/request/generate_request.py
  app/router/generate_router.py
  app/service/generate_service.py
  app/util/parsing.py
  requirements.txt
Labels: 문서, 리팩토링

#19 [ICC-67] 응답 구조 수정
  app/dto/model/problem_set.py
  app/dto/response/generate_response.py
  app/service/generate_service.py
  app/util/create_chunks.py
Labels: 구현

#12 [ICC-48] mcp research
  app/adapter/request_to_bedrock.py
  app/dto/model/problem.py
  app/dto/model/subproblem_set.py
  app/dto/request/search_request.py
  app/router/generate_router.py
  app/service/generate_service.py
Labels: 구현

#26 [ICC-80] 롤백 그리고 에러 응답 수정
  app/main.py
Labels: 리팩토링
